name: Module Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  TF_VERSION: "1.6.6"

jobs:
  module-structure:
    name: Module Structure Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Test Module Structure
        run: |
          echo "Testing module structure compliance..."
          
          echo "Testing networking module..."
          [ -f "modules/networking/main.tf" ] || { echo "Missing main.tf"; exit 1; }
          [ -f "modules/networking/variables.tf" ] || { echo "Missing variables.tf"; exit 1; }
          [ -f "modules/networking/outputs.tf" ] || { echo "Missing outputs.tf"; exit 1; }
          [ -f "modules/networking/README.md" ] || { echo "Missing README.md"; exit 1; }
          
          echo "Testing compute module..."
          [ -f "modules/compute/main.tf" ] || { echo "Missing main.tf"; exit 1; }
          [ -f "modules/compute/variables.tf" ] || { echo "Missing variables.tf"; exit 1; }
          [ -f "modules/compute/outputs.tf" ] || { echo "Missing outputs.tf"; exit 1; }
          [ -f "modules/compute/README.md" ] || { echo "Missing README.md"; exit 1; }
          
          echo "All modules have required structure"

  terraform-syntax:
    name: Terraform Syntax Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: [networking, compute]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Test Module
        run: |
          cd modules/${{ matrix.module }}
          
          echo "Testing module: ${{ matrix.module }}"
          terraform fmt -check
          terraform init -backend=false
          terraform validate
          
          echo "Module ${{ matrix.module }} passed all syntax tests"

  example-validation:
    name: Example Validation
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example: [basic-infrastructure, web-application]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Test Example
        run: |
          cd examples/${{ matrix.example }}
          
          echo "Testing example: ${{ matrix.example }}"
          
          [ -f "main.tf" ] || { echo "Missing main.tf"; exit 1; }
          [ -f "variables.tf" ] || { echo "Missing variables.tf"; exit 1; }
          [ -f "outputs.tf" ] || { echo "Missing outputs.tf"; exit 1; }
          [ -f "terraform.tfvars.example" ] || { echo "Missing terraform.tfvars.example"; exit 1; }
          [ -f "README.md" ] || { echo "Missing README.md"; exit 1; }
          
          terraform fmt -check
          terraform init -backend=false
          terraform validate
          
          echo "Example ${{ matrix.example }} passed validation"

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [module-structure, terraform-syntax, example-validation]
    if: always()

    steps:
      - name: Generate Test Report
        run: |
          echo "Module Testing Summary"
          echo "======================"
          echo ""
          echo "Test Results:"
          echo "- Module Structure: ${{ needs.module-structure.result }}"
          echo "- Terraform Syntax: ${{ needs.terraform-syntax.result }}"
          echo "- Example Validation: ${{ needs.example-validation.result }}"
          echo ""
          
          if [[ "${{ needs.module-structure.result }}" == "success" && 
                "${{ needs.terraform-syntax.result }}" == "success" && 
                "${{ needs.example-validation.result }}" == "success" ]]; then
            echo "ALL TESTS PASSED! Modules are ready for production."
          else
            echo "Some tests failed. Please review and fix issues."
            exit 1
          fi
