name: Security Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  checkov:
    name: Checkov Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          quiet: true
          soft_fail: true

  secrets-scan:
    name: Secrets Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GitLeaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    needs: [checkov, secrets-scan]
    if: always()

    steps:
      - name: Quality Gate Check
        run: |
          echo "Security Scan Results:"
          echo "Checkov: ${{ needs.checkov.result }}"
          echo "Secrets: ${{ needs.secrets-scan.result }}"
          
          if [[ "${{ needs.secrets-scan.result }}" == "failure" ]]; then
            echo "Secrets detected in repository"
            exit 1
          fi
          
          echo "Security checks completed"
